"""Pinned model and corpus configuration for the Nemotron reproduction."""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass

from jlens import Layout


@dataclass(frozen=True)
class NemotronSpec:
    """The exact checkpoint and architecture targeted by this project."""

    model_id: str
    revision: str
    model_type: str
    n_layers: int
    d_model: int
    vocab_size: int
    total_parameters: int
    active_parameters: int
    layout: Layout

    @property
    def source_layer_count(self) -> int:
        """Number of matrices in a default final-layer fit."""
        return self.n_layers - 1

    def artifact_size_gib(self, *, bytes_per_element: int = 2) -> float:
        """Dense lens size for every source layer, excluding serialization overhead."""
        return (
            self.source_layer_count
            * self.d_model
            * self.d_model
            * bytes_per_element
            / 1024**3
        )

    def fit_host_ram_gib(self) -> float:
        """Approximate CPU RAM for fp32 running sum plus per-prompt scratch."""
        return 2 * self.artifact_size_gib(bytes_per_element=4)

    def fit_finalize_host_ram_gib(self) -> float:
        """Core fp32 matrices at finalization: sum, last scratch, and mean."""
        return 3 * self.artifact_size_gib(bytes_per_element=4)

    def streaming_merge_host_ram_gib(self) -> float:
        """Core fp32 matrices while one input lens is added to the accumulator."""
        return 2 * self.artifact_size_gib(bytes_per_element=4)

    def weight_size_gib(self, *, bytes_per_parameter: int = 2) -> float:
        if bytes_per_parameter <= 0:
            raise ValueError("bytes_per_parameter must be positive")
        return self.total_parameters * bytes_per_parameter / 1024**3

    def backward_passes_per_prompt(self, dim_batch: int) -> int:
        if dim_batch <= 0:
            raise ValueError("dim_batch must be positive")
        return math.ceil(self.d_model / dim_batch)

    def to_dict(self) -> dict:
        out = asdict(self)
        out["layout"] = asdict(self.layout)
        return out


# Pinned on 2026-07-06. This is the unified reasoning/instruct checkpoint used
# for the final interactive demo. The base checkpoint remains configurable in
# the CLI, but mixing checkpoints within a fit is rejected by metadata checks.
NEMOTRON = NemotronSpec(
    model_id="nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
    revision="cbd3fa9f933d55ef16a84236559f4ee2a0526848",
    model_type="nemotron_h",
    n_layers=52,
    d_model=2688,
    vocab_size=131072,
    total_parameters=31_600_000_000,
    active_parameters=3_600_000_000,
    layout=Layout(
        path="backbone",
        layers="layers",
        norm="norm_f",
        embed="embeddings",
        lm_head="lm_head",
    ),
)

DEFAULT_DATASET_ID = "Salesforce/wikitext"
DEFAULT_DATASET_CONFIG = "wikitext-103-raw-v1"
DEFAULT_DATASET_REVISION = "b08601e04326c79dfdd32d625aee71d232d685c3"
DEFAULT_DATASET_SPLIT = "train"
DEFAULT_TEXT_FIELD = "text"

# This is the public reference implementation revision imported into this
# repository. Keeping it in metadata makes derived artifacts auditable even if
# this project later advances beyond that commit.
UPSTREAM_JLENS_COMMIT = "581d398613e5602a5af361e1c34d3a92ea82ba8e"

# Paper/open-demo fitting defaults.
DEFAULT_N_PROMPTS = 1000
DEFAULT_MAX_SEQ_LEN = 128
DEFAULT_SKIP_FIRST = 16
DEFAULT_DIM_BATCH = 8

# Scientific artifacts deliberately use fp32 even when the model forward/backward
# pass uses bf16.  The fitted matrices are means over prompts; quantizing each
# shard before a weighted merge changes the result and cannot be undone later.
ARTIFACT_STORAGE_DTYPE = "float32"

# Canonical corpus manifests generated by ``ordered-concatenate-and-chunk-v1``
# from the pinned WikiText revision above.  These hashes are acceptance inputs,
# not merely labels: changing the data, order, or corpus size produces a smoke
# artifact rather than a pilot or paper-scale reproduction.
PILOT_N_PROMPTS = 100
PILOT_CORPUS_MANIFEST_SHA256 = (
    "df38859ae72daab950b93ddd912106138c2ea1b51fc69f6adcc3673c918ccb3d"
)
PAPER_SCALE_N_PROMPTS = 1000
PAPER_SCALE_CORPUS_MANIFEST_SHA256 = (
    "c75fc7ee5d92335f0620a08c6f87d210fc3b3fe4f3d6bcfae7d0cd864a88d63e"
)

ACCEPTANCE_SCHEMA = "nemotron-jlens-acceptance/v1"

# The pinned Nemotron remote implementation was validated against this exact
# Transformers release.  This is a scientific compatibility constraint rather
# than a lower bound: loading with a different remote-code API can change the
# model implementation while retaining the same checkpoint revision.
REQUIRED_TRANSFORMERS_VERSION = "4.57.3"

# Distribution names whose versions form the hardware-independent scientific
# runtime identity embedded in every fitted artifact.  GPU placement remains in
# the separate environment record so shards may run on different devices while
# still requiring identical model software at merge time.
RUNTIME_DISTRIBUTIONS = (
    "transformers",
    "mamba-ssm",
    "causal-conv1d",
    "accelerate",
    "datasets",
    "huggingface-hub",
)

# Settings that affect the fitted scientific result.  Runtime placement and
# checkpoint cadence are intentionally absent: they do not change the fit.
REPRODUCTION_FIT_SETTINGS = {
    "dim_batch": DEFAULT_DIM_BATCH,
    "max_seq_len": DEFAULT_MAX_SEQ_LEN,
    "skip_first": DEFAULT_SKIP_FIRST,
    "dtype": "bfloat16",
    "compile_blocks": False,
    "disable_mamba_kernels": False,
    "mamba_backend": "fused-or-auto",
    "patched_mamba_layers": 0,
}
